parameters:
    stevecohenfr.ez_seo.provider_aggregator.class: SteveCohenFR\EzSeoBundle\Common\ProviderAggregator
    stevecohenfr.ez_seo.seo_provider.class: SteveCohenFR\EzSeoBundle\Services\SteveCohenFRSeoProvider
    stevecohenfr.ez_seo.config.class: SteveCohenFR\EzSeoBundle\Services\ConfigService

services:
    stevecohenfr.ez_seo.provider_aggregator:
        class: '%stevecohenfr.ez_seo.provider_aggregator.class%'
    stevecohenfr.ez_seo.seo_provider:
        class: '%stevecohenfr.ez_seo.seo_provider.class%'
        arguments: ["@ezpublish.api.repository", "@stevecohenfr.ez_seo.provider_aggregator"]
    stevecohenfr.ez_seo.config:
        class: '%stevecohenfr.ez_seo.config.class%'
        arguments: [""]