services:
    stevecohen.ez_seo.provider_aggregator:
        class: SteveCohen\EzSeoBundle\Common\ProviderAggregator
    stevecohen.ez_seo:
        class: SteveCohen\EzSeoBundle\Services\SteveCohenSeoProvider
        arguments: ["@ezpublish.api.repository", "@stevecohen.ez_seo.provider_aggregator"]